apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100
        custom_tags:
          "k8s.cluster.name":
            literal:
              value: tracing-cluster