name: Deploy
#
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ closed ]
  workflow_dispatch:

env:
  ECR: 636334651895.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE: istio-xray

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
        #if: ${{ github.event_name == 'push' }}

      - name: Set env
        run: |
          echo "TAG=${ECR}/${IMAGE}:latest" >> $GITHUB_ENV

      - name: Run build
        run: ./bin/build.sh -t $TAG

      - name: ECR login
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR

      - name: Push image
        run: docker image push $TAG
