name: Deploy Dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ closed ]
  workflow_dispatch:

env:
  ECR: 636334651895.dkr.ecr.eu-central-1.amazonaws.com/polkapad-otelcol-custom-istio-awsxray
  ROLE: "arn:aws:iam::636334651895:role/github-ecr-polkapad-otelcol-custom-istio-awsxray"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
        #if: ${{ github.event_name == 'push' }}

      - name: Set env
        run: |
          echo "TAG=${ECR}:latest" >> $GITHUB_ENV

      - name: Run build
        run: ./bin/build.sh -t $TAG

      - name: Push to ECR and Argo
        uses: ./.github/actions/argo-push
        with:
          aws-role: ${{ env.ROLE }}
          aws-ecr-uri: ${{ env.ECR }}
          ssh-key: ${{ secrets.ARGOCD_REPO_SSH }}
          environment: dev
          project: otelcol_custom_istio_awsxray
          image: ${{ env.TAG }}